name: express
framework: express
language: javascript
package_manager: npm
entrypoint: index.js
app_var: app
aws-lambda:
  region: us-east-1
  role_name: express-role
  runtime: nodejs18.x
gcp-cloudrun:
  region: us-central1
  project_id: upify-438115
  runtime: nodejs18
