name: flask
framework: flask
language: python
package_manager: pip
entrypoint: main.py
app_var: app
aws-lambda:
  region: us-east-1
  role_name: flask-role
  runtime: python3.12
gcp-cloudrun:
  region: us-central1
  project_id: upify-438115
  runtime: python312
